services:
  postgresql:
    image: bitnami/postgresql:16
    environment:
      POSTGRESQL_USERNAME: docker
      POSTGRESQL_PASSWORD: docker
      POSTGRESQL_DATABASE: docker
    ports:
      - 0.0.0.0:5432:5432
    volumes:
      - ./database_setup.sql:/docker-entrypoint-initdb.d/database_setup.sql
